title: Sergey Yurkov
description: 

github_username: sergeyyurkov1
github_repo: "blog"

url: "https://sergeyyurkov1.github.io"
baseurl: "/blog"

minima:
  social_links:
    twitter: 
    github: sergeyyurkov1
    linkedin: sergeyyurkov1

use_math: 

show_description: false

show_image: true

annotations: false

show_tags: true

google_analytics: 

exclude:
  - docker-compose.yml
  - action.yml
  - Makefile

include:
  - _pages

default_badges:
  github: false
  binder: true
  colab: true
  deepnote: true

html_escape:
  description: false

future: true
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-toc
  - jekyll-twitter-plugin
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

paginate: 15
paginate_path: /page:num/

remote_theme: jekyll/minima

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

feed:
  posts_limit: 5 #default posts_limit: 10
  excerpt_only: true

exclude:
  - settings.ini
